### ISSUE TITLE
Error: Mower has not been configured yet

### ISSUE THREAD

**Issue by danholt-international** [normen/homebridge-landroid#12]
Since version 0.6.3 I get this error message and the mower does not start any more: 
[Landroid] Error: Mower has not been configured yet.
[3/16/2020, 13:46:47] [Landroid] Sending to landroid cloud: [{"cmd":1}] (#null)
[3/16/2020, 13:46:47] [Landroid] Try to send a message but could not find the mower

**Comment by normen** [comment]
Yeah, the old library I used didn't connect to the new Worx cloud at all anymore so theres been some changes in the plugin with a new Worx cloud library.

It looks like your mower doesn't get configured, maybe it has a different name than the plugin expects. By default the cloud assigns names from 1-n, the old plugin used numbers from 0-n. Did you change the name of your mower in the Worx app or something or did you falsely specify a `dev_name` as `0`? Then the mower won't be found.

At any instance, to be able to track this down I need some more info. Is there a `Connected to WORX cloud.` message at all? If you could post all output of the plugin from the homebridge boot on and your config.json settings etc., that would help.

**Comment by danholt-international** [comment]
Hello Norman!

Thank you for your prompt reply!

> Am 16.03.2020 um 17:15 schrieb Normen Hansen <notifications@github.com>:
> ...
> It looks like your mower doesn't get configured, maybe it has a different name than the plugin expects. By default the cloud assigns names from 1-n, the old plugin used numbers from 0-n. Did you change the name of your mower in the Worx app or something (I can't even change the names of my two Landroid-S mowers).
> 
Well, I have not changed the mower's name or anything else, except installing the new plugin 0.6.3.

Nevertheless I tried to use dev_name = 0, 1 and 2 for testing. No change.


The original config that worked with the earlier plugins was:

 "platform": "Landroid",
            "landroids": [
                {
                    "name": "Landroid",
                    "email": "daniel@danholt.de",
                    "pwd": „XXXXXXXXXXXXXX",
                    "dev_sel": 0
                }

The current config I installed is this:

    {
            "platform": "Landroid",
            "email": "daniel@danholt.de",
            "pwd": „XXXXXXXXXXXXXXXX",
            "landroids": [
                {
                    "name": "Landroid",
                    "dev_name": "1"
                }
            ]
        },


I tried both configs and 0, 1, 2 as dev_names without any success.

> At any instance, to be able to track this down I need some more info. Is there a Connected to WORX cloud. message at all? If you could post all output of the plugin from the homebridge boot on, that would help.
> 
Well, that works:

[3/17/2020, 09:21:02] [Landroid] Connected to WORX cloud.

[3/17/2020, 09:21:00] Loaded plugin: homebridge-landroid
[3/17/2020, 09:21:00] Registering platform 'homebridge-landroid.Landroid‘

[3/17/2020, 09:21:00] [Landroid] Initializing Landroid platform...
[3/17/2020, 09:21:00] [Landroid] Initializing platform accessory 'Landroid M 700‘…

and the rest not:

[3/17/2020, 09:23:00] [Landroid] Error: Mower has not been configured yet.
[3/17/2020, 09:23:00] [Landroid] Sending to landroid cloud: [{"cmd":1}] (#null)
[3/17/2020, 09:23:00] [Landroid] Try to send a message but could not find the mower


Hope this helps to identify the issue.

Regards

Daniel

**Comment by normen** [comment]
I published a version 0.6.5 which adds a debug mode that logs all reported mowers and data received from the cloud. Please update and add `"debug":true` in config.json. The log should then show all reported mowers with their names.

**Comment by danholt-international** [comment]
Hello Norman!

Here we are:

[3/17/2020, 12:55:27] [Landroid] [DEBUG] MOWER: {"id":364241,"product_id":50,"user_id":175630,"serial_number":"2019301993020000680D","mac_address":"98D8631967EA","name":"M 700","setup_location":{"latitude":48.05732,"longitude":9.61853},"locked":false,"firmware_version":2.92,"firmware_auto_upgrade":true,"distance_covered":158590,"mower_work_time":10078,"blade_work_time":10034,"battery_charge_cycles":61,"messages_in":654,"messages_out":19508,"push_notifications":true,"city":{"id":2953534,"country_id":276,"name":"Bad Buchau","latitude":48.066669,"longitude":9.61667,"created_at":"2018-02-15 22:22:41","updated_at":"2018-02-15 22:22:41"},"sim":null,"push_notifications_level":"warning","lawn_size":118,"lawn_perimeter":null,"raw_messages_in":1711,"raw_messages_out":19508,"test":0,"iot_registered":true,"warranty_registered":true,"pin_code":"0000","time_zone":"Europe/Berlin","purchased_at":"2019-04-20 00:00:00","warranty_expires_at":"2022-04-20 00:00:00","registered_at":"2019-04-25 00:00:00","online":true,"app_settings":null,"accessories":{"ultrasonic":true},"features":{"unrestricted_mowing_time":true,"multi_zone":true,"wifi_connection":"smartlink_display","display_type":"lcd","lock":true,"pin":true,"rain_delay":true,"chassis":"m_2019","mqtt":true,"provisionable":true,"wifi_pairing":"smartlink","tracking_firmware":true,"provisoning_replaceable":true},"auto_schedule_settings":null,"auto_schedule":false,"pending_radio_link_validation":null,"mqtt_topics":{"command_in":"PRM100/98D8631967EA/commandIn","command_out":"PRM100/98D8631967EA/commandOut"},"created_at":"2019-03-22 08:05:04","updated_at":"2020-03-16 12:34:41"}
[3/17/2020, 12:55:29] [Landroid] [DEBUG] DATA: {"cfg":{"id":1,"lg":"it","tm":"12:55:25","dt":"17/03/2020","sc":{"m":1,"p":0,"d":[["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0]]},"cmd":0,"mz":[67,3,0,0],"mzv":[1,1,1,1,1,1,1,1,1,1],"rd":180,"sn":"2019301993020000680D","modules":{"US":{"enabled":1}}},"dat":{"mac":"98D8631967EA","fw":2.92,"bt":{"t":12.7,"v":18.93,"p":99,"nr":63,"c":0,"m":1},"dmp":[0.4,0.2,359.9],"st":{"b":10036,"d":163235,"wt":10367,"bl":71},"ls":1,"le":5,"lz":4,"rsi":-46,"lk":0,"act":1,"conn":"wifi","modules":{"US":{"stat":"ok"}}}}

Regards

Daniel

**Comment by normen** [comment]
Okay, apparently the name of your mower is "M 700"... Did you configure that in the Worx cloud? For my Landroid S I can't even set a name in the Worx app..? Or maybe it was set automatically.

**Comment by normen** [comment]
I updated the plugin so that it always shows the name of mowers that are reported from the cloud, that should make such situations easier.

**Comment by danholt-international** [comment]
Hello Norman!

I have installed 0.6.6 now, but unfortunately still getting this only:

[3/17/2020, 13:09:32] [Landroid] Sending to landroid cloud: [{"cmd":1}] (#2019301993020000680D)
[3/17/2020, 13:09:33] [Landroid] [DEBUG] DATA: {"cfg":{"id":1,"lg":"it","tm":"13:09:32","dt":"17/03/2020","sc":{"m":1,"p":0,"d":[["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0],["11:00",0,0]]},"cmd":0,"mz":[67,3,0,0],"mzv":[1,1,1,1,1,1,1,1,1,1],"rd":180,"sn":"2019301993020000680D","modules":{"US":{"enabled":1}}},"dat":{"mac":"98D8631967EA","fw":2.92,"bt":{"t":13.2,"v":18.9,"p":97,"nr":63,"c":0,"m":1},"dmp":[0.4,0.2,359.9],"st":{"b":10036,"d":163235,"wt":10367,"bl":71},"ls":1,"le":5,"lz":4,"rsi":-45,"lk":0,"act":1,"conn":"wifi","modules":{"US":{"stat":"ok"}}}}

Problem is, that the worx software wants a name here:



I tried now „M700“, M 700, and a single „1“ with no success.

Regards

Daniel

**Comment by normen** [comment]
Well that looks as if the plugin did its work correctly now. `"dev_name": "M 700"` should be correct for your config.json.

From what I see in the log the plugin correctly found the name, grabbed the serial number and used it when sending the command. Maybe theres some other issue with the mower at the moment? Rain?

**Comment by danholt-international** [comment]
Well, got it.
Renamed again and mower restartet and it works now as „M700“ without space (M 700).

Thanks for your kind assistance and your great work!

Regards

Daniel

**Comment by normen** [comment]
Hm, thats strange, it really should be "M 700" with a space if your first log is correct. Maybe theres some strangeness in your config.json saving and homebridge restarting order? Like the config.json you think you apply on this restart is only applied on the next restart?

**Comment by danholt-international** [comment]
No, all correct as I changed the name to M700 in worx app too during the testing.
Just to make sure that the SPACE makes no trouble.

Regards

Daniel

**Comment by normen** [comment]
Ah, that makes sense. Thanks for the help improving the plugin!
